name: Build OmniRoute for HuggingFace

on:
  workflow_dispatch:
    inputs:
      ref:
        description: Branch to build
        required: true
        default: main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Test workflow'
